FROM ubuntu:22.
RUN apt update && apt install -y cmake g++
WORKDIR /app
COPY . .
RUN crpn_calculator && cmake -B build && cmake --build build
CMD ["/app/rpn_calculator/build/rpn_calculatorFROM ubuntu:22.04
RUN apt update && apt install -y cmake g++
WORKDIR/app
COPY . .RUN cd rpn_calculator && cmake -B build && cmake --build build
CMD ["/app/rpn_calculator/build/rpn_calculator"]
